# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Form
  description: Form section
  icon: "check_box"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  address:
    heading: Dirección
    address: "Calle 17 # 8-52 Interlaken Av. Guabinal"
  phone:
    heading: "Teléfono"
    cell: "3138825184"
    image: /images/contact/call-add.svg
    image_alt: call-add
  email:
    heading: "Email"
    email: "convergenciadigitalsas@gmail.com"
    image: /images/contact/directbox-send.svg
    image_alt: send-box
  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: 
  fullname:
    options:
      preview:
        icon: person
  phone:
    options:
      preview:
        icon: phone
  email:
    options:
      preview:
        icon: email
  message:
    options:
      preview:
        icon: drive_file_rename_outline
  submit_button:
    options:
      preview:
        icon: send